We are utilizing Transformer as a pretrained model for:
- Text Classification
- Text Generation

In [1]:
text1='''Extremely disappointed with the recent purchase of IPhone 17 from Apple.
This device constantly lags and the battery is not upto the mark. It barely lasts through the day.'''

text2='''I recently purchased an IPhone from Apple and it has been an absolute delight.
This device runs smoothly and the battery life is impressive. The price, though high, is justified by the
excellent performance and top notch customer support'''

In [3]:
from transformers import pipeline #pipelines in transfomers are different for different usecases
#e.g. pipeline of text classification is very different from text generation

classifier=pipeline('text-classification') #we need to explicitly specify

import pandas as pd

output1=classifier(text1)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [4]:
pd.DataFrame(output1)

      label     score
0  NEGATIVE  0.999708

In [5]:
output2=classifier(text2)

In [6]:
pd.DataFrame(output2)

      label     score
0  POSITIVE  0.999849

In [7]:
generator=pipeline('text-generation')
response="Dear valued customer, thanks for writing!I am sorry to hear your experience with us"
prompt=text1+'\n\Customer Service Response:\n'+response

output=generator(prompt,max_length=100)
#along with the response, Transformer will add 100 tokens to complete the message

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
/tmp/ipykernel_4010/1924617543.py:3: SyntaxWarning: invalid escape sequence '\C'
  prompt=text1+'\n\Customer Service Response:\n'+response
No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Passing `generation_config` together with generation-related arguments=({'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=100) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [8]:
print(output)

[{'generated_text': 'Extremely disappointed with the recent purchase of IPhone 17 from Apple.\nThis device constantly lags and the battery is not upto the mark. It barely lasts through the day.\n\\Customer Service Response:\nDear valued customer, thanks for writing!I am sorry to hear your experience with us. I am not a phone manufacturer and have a bad experience with the IPhone 17. I have tried various products from Apple, as I am a person who does not like to write about electronics. The IPhone 17 was the best product we have ever received and I have been using it ever since. I do not have any problems with the battery, it has been working for a very long time. If you are a user of this device please let me know, if your feedback is good, please get in touch with me. As I said before, my phone was very happy with the purchase of the IPhone 17. We have been able to get our IPhone 17 to working for about 2 weeks now. I have been using it for about 3 months now and am able to use it a lot. The battery is getting much better. I will definitely be using it to recharge my iPhone and iPad. This is the only phone that I have purchased that uses a charger. The charger is a great deal and we have been using it on multiple occasions.I have ordered the IPhone 17 from Apple and it has worked great. I will definitely be using it to charge my iPhone and iPad. Thank you for your time and support in the past.\n\\Customer Service'}]